apiVersion: v1
kind: Service
metadata:
  name: syspass-public
spec:
  selector:
    app: syspass-app
  ports:
  - port: 80
    targetPort: 80
    name: syspassport
  - port: 443
    targetPort: 443
    name: syspassport-https
  type: LoadBalancer
